<center><h1>NumPy</h1></center>

### What is NumPy?
> NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms (audio analytics), basic linear algebra, basic statistical operations, random simulation and much more.
- NumPy stands for <b>NUM</b>erical <b>PY</b>thon
- Basically used for numerical computations.
- It is iterable.
- It is mutable.
- It can only have homogeneous data in it (i.e. all the elements have to be of the same datatype.)

### Why Numpy arrays overs lists and tuples?
> - Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code.
> - It is faster compared to List and Tuple when it comes to large datasets.
> - It is convinient for a lot of tasks having more number of dimentions
> - it consumes less memory

> Documnetation Link : https://numpy.org/doc/stable/index.html

In [1]:
# to install packages directly from the notebook.
# !pip install numpy

In [2]:
# import the library for using it in the notebook
# np is an alias that makes it easier to use (you can provide any other alias)

import numpy as np
print('package successfully imported')

package successfully imported


In [3]:
# creating a 1D array from a list

list_var = [1,2,3,4,5]
print(type(list_var))
print(list_var,end='\n\n')

list_to_array = np.array([1,2,3,4,5])
print(type(list_to_array))
print(list_to_array)

<class 'list'>
[1, 2, 3, 4, 5]

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
# creating a 1D array from a tuple

tuple_var = (1,2,3,4,5)
print(type(tuple_var))
print(tuple_var,end='\n\n')

tuple_to_array = np.array((1,2,3,4,5))
print(type(tuple_to_array))
print(list_to_array)

<class 'tuple'>
(1, 2, 3, 4, 5)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
# homogenious data:
# decimal numbers have a greater order compared to whole numbers

list_var = [1, 2, 3, 4, 5.5, 6.0]
print(type(list_var))
print(list_var,end='\n\n')

list_to_array = np.array(list_var)
print(type(list_to_array))
print(list_to_array)

<class 'list'>
[1, 2, 3, 4, 5.5, 6.0]

<class 'numpy.ndarray'>
[1.  2.  3.  4.  5.5 6. ]


In [6]:
# string data type have a greater order than decimal and whole numbers
list_var = [1,2,3,4,5.5, 6.0, 'e']
print(type(list_var))
print(list_var,end='\n\n')

list_to_array = np.array(list_var)
print(type(list_to_array))
print(list_to_array)

<class 'list'>
[1, 2, 3, 4, 5.5, 6.0, 'e']

<class 'numpy.ndarray'>
['1' '2' '3' '4' '5.5' '6.0' 'e']


# Dimentions in arrays:
<img src='https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png' width=500dp>


Image Reference: https://predictivehacks.com/

In [7]:
# 2d Array: multiple 1d array will make a 2d array.

array_2d = np.array([[5.2, 3.0, 4.5],[9.1, 0.1, 0.3]])
print('array_2d: ',array_2d, sep='\n\n')

array_2d: 

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [8]:
# 3d Array: Multiple 2d arrays will make a 3d array

array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('array_3d:',array_3d,sep='\n\n')

array_3d:

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### How is Numpy better

In [14]:
list_1 = [1, 2, 3, 4, 5, 9]
list_2 = [6, 7, 8, 9, 10, 11]
sum_list = []

# the shotter way:
length_1 = len(list_1)
length_2 = len(list_2)
min_length = min(length_1, length_2)

for i in range(0, length_1):
    sum_list.append(list_1[i]+list_2[i])
    
print("Sum list:", sum_list, sep='\n')

Sum list:
[7, 9, 11, 13, 15, 20]


In [16]:
# optimal method:
list_1 = [1, 2, 3, 4, 5, 10]
list_2 = [6, 7, 8, 9, 10]
sum_list = []

sum_list = list(map(lambda x, y : x+y, list_1, list_2))
print("Sum list:", sum_list, sep='\n')

Sum list:
[7, 9, 11, 13, 15]


In [19]:
# using numpy: Vectorised Code
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6, 7, 8, 9, 10])
sum_list = array_1+array_2

print("Sum list:", sum_list, sep='\n')

Sum list:
[ 7  9 11 13 15]


In [20]:
# conditon to check 
array_1_bool = array_1 >= 3
print('checking for the condition:', array_1_bool,end='\n\n')
print('what are the values that satisfy the condtion: ',array_1[array_1_bool])

checking for the condition: [False False  True  True  True]

what are the values that satisfy the condtion:  [3 4 5]


In [21]:
# simplyfing the above cloud:
array_1[array_1>2]

array([3, 4, 5])

In [22]:
# operations on higher levels:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])

print('1st array: ',arr1, sep='\n', end='\n\n')
print('2nd array: ',arr2, sep='\n', end='\n\n')
print('final array: ',arr2-arr1, sep='\n', end='\n\n')

1st array: 
[[1 2 3]
 [4 5 6]]

2nd array: 
[[11 12 13]
 [14 15 16]]

final array: 
[[10 10 10]
 [10 10 10]]



### Functions:

In [23]:
# Arange function. (increment factor)
arange_array = np.array(list(range(1,15,2)))
print('using complex nested functions: ', arange_array, end='\n\n')

arange_array = np.arange(1,15,2)
print('using simple numpy functions: ', arange_array)

using complex nested functions:  [ 1  3  5  7  9 11 13]

using simple numpy functions:  [ 1  3  5  7  9 11 13]


In [25]:
# Arange function. (decrement factor)
arange_array = np.arange(15,0,-2)
print('using simple numpy functions: ', arange_array)

using simple numpy functions:  [15 13 11  9  7  5  3  1]


In [31]:
# an array with only zeros:
zero_array_1d = np.zeros(5)
print('1D array:', zero_array_1d,sep='\n', end='\n\n')

zero_array_2d = np.zeros([5,5], dtype=int)
print('2D array:', zero_array_2d,sep='\n', end='\n\n')

1D array:
[0. 0. 0. 0. 0.]

2D array:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



In [32]:
# an array with only ones:
one_array_1d = np.ones(5)
print('1D array:', one_array_1d,sep='\n', end='\n\n')

one_array_2d = np.ones((5,5), dtype=int)
print('2D array:', one_array_2d,sep='\n', end='\n\n')

1D array:
[1. 1. 1. 1. 1.]

2D array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]



In [33]:
# for numbers other than 1 and 0
print(np.full(shape = 5, fill_value=5), end='\n\n')
print(np.full(shape = (5,5), fill_value=3))

[5 5 5 5 5]

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [36]:
# random value
np.random.random((3,3))

array([[0.72782105, 0.26105014, 0.67546676],
       [0.06422386, 0.87701604, 0.9557208 ],
       [0.59421917, 0.41441455, 0.05570997]])

In [45]:
# random.randint and seed significance.
np.random.seed(2)
print(np.random.randint(low = 1, high = 15, size = 10))
np.random.randint(low = 1, high = 15, size = (3,3))

[ 9 14  9  7 12  3 12  9  8  3]


array([[ 2, 12,  6],
       [11,  5, 13],
       [ 5,  6,  8]])

In [51]:
# identity matrix
# important
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [57]:
# we use linspace when the range and the size of the output is known but the stepsize is not known.
# important
arr_1 = np.linspace(1,40,6, dtype=int)
print(arr_1)
arr_1.shape

[ 1  8 16 24 32 40]


(6,)

In [59]:
# make the linspace array into 2 dimentions array
np.linspace(1,40,6, dtype=int).reshape(2,3)

array([[ 1,  8, 16],
       [24, 32, 40]])

In [61]:
# repeat a squence to create a new array
print('1D: ',np.tile([1,2,3],2),sep='\n',end='\n\n')

print('2D: ',np.tile([1,2,3],(3,3)), sep='\n')

1D: 
[1 2 3 1 2 3]

2D: 
[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [62]:
array_1 = np.tile([1,2,3],(3,1))
array_2 = np.arange(2,19,2).reshape(3,3)

print('array 1:',array_1,sep='\n',end='\n\n')
print('array 2:',array_2,sep='\n',end='\n\n')
print('final array:',array_1+array_2,sep='\n')

array 1:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

array 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

final array:
[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]


In [ ]:
# your code goes here


### Structure :

In [64]:
array = np.tile([1,2,3],(3,1))
print(array, end='\n\n')
print('data type',array.dtype)
print('data shape',array.shape)
print('data number of dimentions',array.ndim)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

data type int32
data shape (3, 3)
data number of dimentions 2


In [72]:
# Indexing subsetting and slicing

print('first row: ',array[1])
print('0th elements: ',array[1][0])
print('0th elements: ',array[1,0])
print('first 2 elements : ',array[1,:2])
print('reverse of the first row: ',array[0,::-1])

first row:  [1 2 3]
0th elements:  1
0th elements:  1
first 2 elements :  [1 2]
reverse of the first row:  [3 2 1]


In [ ]:
# your code goes here


## Testing the execution speed:

In [74]:
# this is another pre-built module in python which helps you measure time.
import time 

In [75]:
# performing an operation for list
list_1 = [i for i in range(200000)]
list_2 = [j**2 for j in range(200000)]

# starting the clock
list_start_time = time.time()
list_mul = list(map(lambda x, y: x*y, list_1, list_2))
list_end_time = time.time()
print('total time consumed: ', list_end_time - list_start_time)

total time consumed:  0.028917551040649414


In [76]:
# performing an operation for array
array_1 = np.array([i for i in range(200000)])
array_2 = np.array([j**2 for j in range(200000)])

# starting the clock
array_start_time = time.time()
array_mul = array_1*array_2
array_end_time = time.time()
print('total time consumed: ', array_end_time - array_start_time)

total time consumed:  0.0009975433349609375


In [77]:
list_time = list_end_time - list_start_time
array_time = array_end_time - array_start_time
print(list_time - array_time)

0.027920007705688477
